services:
  dedicated:
    image: evoesports/trackmania:latest
    restart: always
    environment:
      TM_MASTERSERVER_LOGIN: ${TM_MASTERSERVER_LOGIN}
      TM_MASTERSERVER_PASSWORD: ${TM_MASTERSERVER_PASSWORD}
      TM_SERVER_NAME: Match Server
      TM_SERVER_PASSWORD: ${TM_SERVER_PASSWORD}
      TM_SYSTEM_XMLRPC_ALLOWREMOTE: "true"
      TM_SYSTEM_FORCE_IP_ADDRESS: "${TM_SYSTEM_FORCE_IP_ADDRESS}:2350"
      TM_AUTHORIZATION_SUPERADMIN_PASSWORD: ${TM_AUTHORIZATION_SUPERADMIN_PASSWORD}
      TM_AUTHORIZATION_ADMIN_PASSWORD: ${TM_AUTHORIZATION_ADMIN_PASSWORD}
      TM_AUTHORIZATION_USER_PASSWORD: ${TM_AUTHORIZATION_USER_PASSWORD}
    ports:
      - 2350:2350/tcp
      - 2350:2350/udp
      - 5000:5000/tcp
    healthcheck:
      test: ["CMD", "lsof", "-i:2350"]
      start_period: 5s
      interval: 30s
      timeout: 10s
      retries: 3
    volumes:
      - user-data:/server/UserData
  filemanager:
    image: marijnregterschot/trackmania-server-fm:latest
    restart: always
    ports:
      - 3300:3300/tcp
    environment:
      FM_PASSWORD: ${FM_PASSWORD}
    depends_on:
      dedicated:
        condition: service_healthy
    volumes:
      - user-data:/app/UserData

  pyplanet:
    image: pyplanet/pyplanet:latest
    restart: always
    environment:
      PY_ADMINS: ${PY_ADMINS}
      DB_NAME: ${DB_NAME}
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DEDI_HOST: dedicated
      DEDI_PORT: 5000
      DEDI_USER: SuperAdmin
      DEDI_PASS: ${TM_AUTHORIZATION_SUPERADMIN_PASSWORD}
    volumes:
      - ./base.py:/app/server/settings/base.py
      - pyplanet-data:/app/server
      - user-data:/server/UserData
    depends_on:
      - dedicated

volumes:
  user-data:
  pyplanet-data:
