import { normalize } from "./text";
import type { ToolCategory } from "./types";

const keywords: Record<ToolCategory, string[]> = {
  maps: [
    "map",
    "maps",
    "track",
    "tmx",
    "exchange",
    "queue",
    "jukebox",
    "skip",
    "next",
    "restart",
    "replay",
    "jump",
    "play",
    "snow",
    "rally",
    "desert",
    "stadium",
    "car",
    "tech",
    "fullspeed",
    "dirt",
    "ice",
    "grass",
    "plastic",
    "rpg",
    "trial",
    "lol",
    "author",
    "random",
    "awarded",
    "newest",
  ],
  mode: [
    "mode",
    "cup",
    "rounds",
    "round",
    "timeattack",
    "ta",
    "knockout",
    "ko",
    "laps",
    "lap",
    "teams",
    "team",
    "champion",
    "points",
    "point",
    "limit",
    "setting",
    "settings",
    "warmup",
    "warm",
    "pause",
    "unpause",
    "resume",
    "finish",
    "timeout",
    "winners",
    "match",
  ],
  players: [
    "kick",
    "ban",
    "unban",
    "blacklist",
    "unblacklist",
    "guest",
    "guests",
    "spectator",
    "spectate",
    "spec",
    "player",
    "points",
    "point",
    "team",
    "blue",
    "red",
    "force",
  ],
  plugins: [
    "plugin",
    "plugins",
    "enable",
    "disable",
    "turn",
    "widget",
    "reload",
    "config",
    "configure",
  ],
  server: [
    "server",
    "name",
    "rename",
    "comment",
    "description",
    "slots",
    "max",
    "announce",
    "announcement",
    "tell",
    "say",
    "message",
    "everyone",
  ],
  info: [
    "list",
    "show",
    "who",
    "what",
    "which",
    "how",
    "record",
    "records",
    "wr",
    "pb",
    "best",
    "players",
    "online",
    "current",
    "status",
    "help",
    "explain",
    "does",
  ],
};

// Categories whose keywords appear in the text; all of them when none do
export function routeCategories(text: string): ToolCategory[] {
  const words = new Set(normalize(text).split(" "));
  const hits = (Object.keys(keywords) as ToolCategory[]).filter((category) =>
    keywords[category].some((word) => words.has(word)),
  );
  if (text.includes("?") && !hits.includes("info")) hits.push("info");
  return hits.length > 0 ? hits : (Object.keys(keywords) as ToolCategory[]);
}
