services:
  dedicated:
    image: evoesports/trackmania:latest
    restart: unless-stopped
    ports:
      - 2350:2350/udp
      - 2350:2350/tcp
    environment:
      TM_MASTERSERVER_LOGIN: 
      TM_MASTERSERVER_PASSWORD: 
      TM_SYSTEM_XMLRPC_ALLOWREMOTE: True
    volumes:
      - user-data:/server/UserData

  db:
    image: mariadb:latest
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: secret
      MARIADB_USER: evosc
      MARIADB_PASSWORD: evosc
      MARIADB_DATABASE: evosc
    volumes:
      - db-data:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d

  evosc:
    image: evotm/evosc:latest
    restart: unless-stopped
    environment:
      DB_HOST: db
      DB_NAME: evosc
      DB_USER: evosc
      DB_PASSWORD: evosc
      RPC_IP: dedicated
      RPC_LOGIN: SuperAdmin
      RPC_PASSWORD: SuperAdmin
    volumes:
      - evosc-data:/controller
      - user-data:/server/UserData
    depends_on:
      - dedicated
      - db
  
  gocontrolpanel:
    image: marijnregterschot/gocontrolpanel:latest
    build:
      context: ./../..
      dockerfile: Dockerfile
      args:
        - DATABASE_URL=mysql://gocontrolpanel:VettePanel123@db:3306/gocontrolpanel
        - DB_TYPE=mysql
    ports:
      - 3000:3000
    restart: unless-stopped
    environment:
      NEXTAUTH_URL: http://localhost:3000
      NEXTAUTH_SECRET: 
      DEFAULT_ADMINS: 
      DEFAULT_PERMISSIONS: 
      NADEO_CLIENT_ID: 
      NADEO_CLIENT_SECRET: 
      NADEO_REDIRECT_URI: http://localhost:3000/api/auth/callback/nadeo
      NADEO_SERVER_LOGIN: 
      NADEO_SERVER_PASSWORD: 
      NADEO_CONTACT: GoControlPanel / <your contact info>
      REDIS_URI: redis://redis:6379
      HETZNER_KEY: 
    depends_on:
      - db
      - redis

  filemanager:
    image: marijnregterschot/trackmania-server-fm:latest
    restart: unless-stopped
    volumes:
      - user-data:/app/UserData

  redis:
    image: redis:latest
    restart: unless-stopped
    volumes:
      - redis-data:/data

volumes:
  user-data:
  db-data:
  redis-data:
  evosc-data: