// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import DataConnectionSettings from "./data_connection_settings_type";


// The tagged union or sum type for the algebraic type `ConnectionSettings`.
const ConnectionSettings = __t.enum("ConnectionSettings", {Waiting: __t.unit(),
  get Data() {
    return DataConnectionSettings;
  },
});

export default ConnectionSettings;


