services:
  gocontrolpanel:
    image: marijnregterschot/gocontrolpanel:latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - CONNECTOR_URL=http://gbxconnector:6980 # Use the internal Docker network for communication
        - NEXT_PUBLIC_CONNECTOR_URL=http://localhost:6980 # Use the external URL for the frontend
        - DATABASE_URL=mysql://gocontrolpanel:VettePanel123@db:3306/gocontrolpanel
        - DB_TYPE=mysql
    restart: unless-stopped
    ports:
      - 3000:3000
    environment:
      NEXTAUTH_URL: http://localhost:3000
      NEXTAUTH_SECRET: 
      CONNECTOR_API_KEY: 
      DEFAULT_ADMINS: 
      NADEO_CLIENT_ID: 
      NADEO_CLIENT_SECRET:  
      NADEO_REDIRECT_URI: http://localhost:3000/api/auth/callback/nadeo
      NADEO_SERVER_LOGIN: 
      NADEO_SERVER_PASSWORD: 
      NADEO_CONTACT: GoControlPanel / <your contact info>
      REDIS_URI: redis://redis:6379
    depends_on:
      - db
      - redis

  gbxconnector:
    image: marijnregterschot/gbxconnector:latest
    restart: unless-stopped
    ports:
      - 6980:6980
    environment:
      PORT: 6980
      CORS_ORIGINS: "http://localhost:3000"
      SERVER_RECONNECT_INTERVAL: 15
      JWT_SECRET: 
      INTERNAL_API_KEY: 
      LOG_LEVEL: DEBUG
    volumes:
      - ./servers.json:/app/servers.json

  dedicated-server:
    image: evoesports/trackmania:latest
    restart: unless-stopped
    ports:
      - 2350:2350/udp
      - 2350:2350/tcp
    environment:
      TM_MASTERSERVER_LOGIN: 
      TM_MASTERSERVER_PASSWORD: 
      TM_SYSTEM_XMLRPC_ALLOWREMOTE: True
    volumes:
      - user-data:/server/UserData

  filemanager:
    image: marijnregterschot/trackmania-server-fm:latest
    restart: unless-stopped
    volumes:
      - user-data:/app/UserData

  db:
    image: mariadb:latest
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: password_whatever
      MARIADB_USER: gocontrolpanel
      MARIADB_PASSWORD: VettePanel123
      MARIADB_DATABASE: gocontrolpanel
    volumes:
      - db-data:/var/lib/mysql

  redis:
    image: redis:latest
    restart: unless-stopped
    volumes:
      - redis-data:/data

volumes:
  db-data:
  redis-data:
  user-data:
