services:
  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    command:
      - -c client_encoding=UTF8
      - -c log_statement=all
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: