name: NextJS Build Check

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        db: [mysql, postgres]

    env:
      DB: ${{ matrix.db }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache Bun dependencies
        uses: actions/cache@v4
        with:
          path: ~/.bun/install/cache
          key: bun-${{ runner.os }}-${{ hashFiles('bun.lockb') }}
          restore-keys: |
            bun-${{ runner.os }}-

      - name: Install Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Generate Prisma Client for ${{ matrix.db }}
        run: bun run generate

      - name: Cache Next.js build cache
        uses: actions/cache@v4
        with:
          path: .next/cache
          key: nextjs-${{ matrix.db }}-${{ runner.os }}-${{ hashFiles('**/*.[jt]s', '**/*.json', 'next.config.js') }}
          restore-keys: |
            nextjs-${{ matrix.db }}-${{ runner.os }}-

      - name: Build project for ${{ matrix.db }}
        run: bun run build
